### ISSUE TITLE
What is the link for the documentation?

### ISSUE THREAD

**Issue by Zentrik** [JuliaSpace/SatelliteAnalysis.jl#2]

**Comment by ronisbr** [comment]
Hi @Zentrik !

This package is under construction. I will move the analysis algorithms from SatelliteToolbox to this package. It still lacks documentation. Sorry about that.

**Comment by minecraft2048** [comment]
Is there any documentation yet?

**Comment by ronisbr** [comment]
Hi @minecraft2048 !

I still was not able to write the documentation. However, the functions themselves are well documented. Sorry about that.
