### ISSUE TITLE
Strange behaviour in gap/access start/end measurement 

### ISSUE THREAD

**Issue by mcontim** [JuliaSpace/SatelliteAnalysis.jl#3]
Hi @ronisbr! 

Performing some comparison with `SatelliteAnalysis.jl` while developing a tool for measuring continuous accesses from a satellite constellation, I noticed a weird behaviour from the functions `ground_facility_accesses` and `ground_facility_gaps`.

I will try to explain a bit the steps I followed. I paste a code from a `Pluto` notebook which should be helpuful to reproduce the problem. My apologies in advance for not startin directly a PR trying to solve the issue, but I still didn't have time to work on it and I wanted to make you aware of this behaviour before digging deeper in the code.

- The cell with `# Reproduce error with TEME-PEF` gives 2 ambiguous gaps (first 2 lines of `gap1`) which are not separated by an access instead of a continuous gap.
- Maybe the problem is in the function `is_ground_facility_visible`, there some ecef vectors combinations that create the weird behaviour.
- Changing the function for ECI->ECEF conversion seems to solve the problem (parameter of `ground_facility_accesses` to `f_eci_to_ecef=_eci_to_ecef`).
- However, I also found other combinations creating the problem even when different CRS are used for the conversion. Looking at `# Reproduce error with J2000-ITRF` you can in fact see that we obtain 2 separate gaps (instead of a single one) even if there are no accesses.

I hope this helps. Please let me know if you have any insight on this, I can try to further investigate this.

Cheers,
Matteo

```julia
# ╔═╡ 050cd578-1e9b-11ef-0fef-896ab98cae53
using SatelliteAnalysis

# ╔═╡ 927b7a96-c5f4-471d-9d97-6eb6f20b61f5
epoch = DateTime("2024-01-01")

# ╔═╡ 3888d0fe-3358-4f48-95dd-e4de2713b6be
gs = (0.0,0.0,0.0)

# ╔═╡ 0666d926-7546-4ce3-8d93-db43809615dd
# Reproduce error with TEME-PEF
acc1,gap1 = let
	
	orbElem = KeplerianElements(
				epoch |> datetime2julian, # t
				7878.14e3, # a
				0.0, # e
				deg2rad(60), # i
				0.0, # Ω
				0.0, # ω
				0.0 # f
			)
	
	orbp = Propagators.init(Val(:J2), orbElem)

	acc = ground_facility_accesses(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=120)

	gap = ground_facility_gaps(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=120)

	acc,gap
end

# ╔═╡ 25219f14-0e7e-429f-abdb-662a233f2d17
# Reproduce error with J2000-ITRF
acc2,gap2 = let
	eop_iau1980 = fetch_iers_eop(Val(:IAU1980));
	
	function _eci_to_ecef(r_i::AbstractVector, jd::Number)
		R = r_eci_to_ecef(J2000(), ITRF(), jd, eop_iau1980)
		return R*r_i
	end
	
	orbElem = KeplerianElements(
				epoch |> datetime2julian, # t
				6878.14e3, # a
				0.0, # e
				deg2rad(20), # i
				0.0, # Ω
				0.0, # ω
				0.0 # f
			)

	orbp = Propagators.init(Val(:J2), orbElem)

	acc = ground_facility_accesses(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=120, f_eci_to_ecef=_eci_to_ecef)

	gap = ground_facility_gaps(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=120, f_eci_to_ecef=_eci_to_ecef)

	acc,gap
end
```

**Comment by ronisbr** [comment]
Hi @BlueTeo91 !

Sorry for the delay, I missed the notification.

Thanks for the issue report :) In fact, the problem was caused because the gap function computes the accesses using the standard step time (60s) instead of the one provided.

If you use a step of 120s in this case, you loose a very small access:

```julia
julia> acc = ground_facility_accesses(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=1)
2×3 DataFrame
 Row │ access_beginning         access_end               duration
     │ DateTime                 DateTime                 Float64
─────┼────────────────────────────────────────────────────────────
   1 │ 2024-01-01T04:48:35.564  2024-01-01T04:49:22.062    46.498
   2 │ 2024-01-01T17:22:37.141  2024-01-01T17:26:07.039   209.898

julia> acc = ground_facility_accesses(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=10)
2×3 DataFrame
 Row │ access_beginning         access_end               duration
     │ DateTime                 DateTime                 Float64
─────┼────────────────────────────────────────────────────────────
   1 │ 2024-01-01T04:48:35.563  2024-01-01T04:49:22.062    46.499
   2 │ 2024-01-01T17:22:37.140  2024-01-01T17:26:07.039   209.899

julia> acc = ground_facility_accesses(orbp, gs; minimum_elevation=deg2rad(60), duration=24*3600, step=120)
1×3 DataFrame
 Row │ access_beginning         access_end               duration
     │ DateTime                 DateTime                 Float64
─────┼────────────────────────────────────────────────────────────
   1 │ 2024-01-01T17:22:37.141  2024-01-01T17:26:07.039   209.898
```

By changing the reference system, you obtain different scenarios that might or might not work because the function that computes the accesses might find or miss a very small access (lower than 60s).

Hence, the bug should be fixed by passing the `step` you provided in the gap calculation to the access function. I will submit a commit shortly.

Thanks one more time for the issue report!

**Comment by ronisbr** [comment]
@BlueTeo91 done! Can you please test against `main` before I tag a new release?

**Comment by mcontim** [comment]
Great @ronisbr! Thanks you very much for the quick action. I see now the accesses and gap lists are consistent.

I also noticed a mismatch in access/gaps duration and start/end, which is possibly due to an inaccuracy in the elevation computation in `is_ground_facility_visible`. For this I opened another issue #4
