### ISSUE TITLE
Possible inaccuracy in elevation computation in is_ground_facility_visible

### ISSUE THREAD

**Issue by mcontim** [JuliaSpace/SatelliteAnalysis.jl#4]
Hi @ronisbr!

I found a possible inaccuracy in the computation of the elevation angle in `is_ground_facility_visible`, which might lead to some errors in the start/end and duration estimation of accesses/gaps.

```julia
function is_ground_facility_visible(
    sat_r_e::AbstractVector,
    gf_r_e::AbstractVector,
    θ::Number
)
    # Check if the satellite is within the visibility circle of the facility.
    Δr_e = sat_r_e - gf_r_e
    cos_β = dot(Δr_e / norm(Δr_e), gf_r_e / norm(gf_r_e))

    return cos_β > cos(π / 2 - θ)
end
```

It seems that the ECEF vector `gf_r_e` is computed taking into account the ellipsoid in `geodetic_to_ecef`, however, the computation of `cos_β` appears to be done on a sphere instead of an ellipsoid, taking into account the Local Tangent Plane for that coordinates (i.e., the `gf_r_e` is aligned with the pi/2 elevation direction for that coordinates).

I hope this is an ok explanation of the issue, I'm working on a PR such to verify I'm not wrong and try to fix it :D 

Do you have any insight on this? Maybe I missed some details in the code.

**Comment by mcontim** [comment]
Just a quick update, I think I solved the issue, I will open a PR (just need to clean a bit the code :D)

**Comment by ronisbr** [comment]
Hi @BlueTeo91 !

I did not think a lot about, but it seems your point is valid! Thanks for working on this issue :)

**Comment by ronisbr** [comment]
Hi @mcontim !

I clean up the code and tag a new version. I tested the results compared with another software and the precision is definitely improved! Awesome work! Thank you very much.

**Comment by ronisbr** [comment]
Hi @mcontim !

I need your help. I just pushed a commit to `main` that enabled melt-threaded computation for the algorithm to compute the accesses. Can you please test to check if you can find some regression? Thanks!
